version: v1.0
name: CI
agent:
  machine:
    type: ''
    os_image: ''
'on': push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: 'docker run --rm aitesla/ai:ai'
blocks: []
